config/routes.rb
Rails.application.routes.draw do
  root to: 'microposts#index'
  get '/', to: 'pages#home'
  get '/help', to: 'pages#help'
  get '/about', to: 'pages#about'
  get '/terms_of_service', to: 'pages#terms_of_service'
  get '/privacy', to: 'pages#privacy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get 'timeline', to: 'microposts#timeline'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  post 'likes/:micropost_id/create', to: 'likes#create', constraints: { micropost_id: /\d+/ }, as: :likes_create
  post 'likes/:micropost_id/destroy', to: 'likes#destroy', constraints: { micropost_id: /\d+/ }, as: :likes_destroy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  validates :user_id, presence: true
  validates :micropost_id, presence: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new(user_id: @current_user.id, micropost_id: params[:micropost_id])
    @like.save
    @micropost = Micropost.find_by(id: @like.micropost_id)
    @like_count = Like.where(micropost_id: params[:micropost_id]).count
  end

  def destroy
    @like = Like.find_by(user_id: @current_user.id, micropost_id: params[:micropost_id])
    @micropost = Micropost.find_by(id: @like.micropost_id)
    @like.destroy
    @like_count = Like.where(micropost_id: params[:micropost_id]).count
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if logged_in? %>
  <% if current_user.like?(micropost) %>
    <div class="like_button_on">
      <%= link_to likes_destroy_path(micropost_id: micropost.id), {method: "post", remote: true} do %>
        <%= image_tag 'kodawarimedia-1.jpeg', alt: イイネ %>
      <% end %>
    </div>
    <span class="likes_count"><%= @like_count %>likes</span>
  <% else %>
    <div class="like_button">
      <%= link_to likes_create_path(micropost_id: micropost.id), {method: "post", remote: true} do %>
        <%= image_tag 'edit.jpeg', alt: イイネ %>
      <% end %>
    </div>
    <span class="likes_count"><%= @like_count %>likes</span>
  <% end %>
<% else %>
  <%= like_to new_user_session_path, method: :get do %>
    <%= image_tag 'default.jpeg', alt: イイネ %>
  <% end %>
  <span class="likes_count"><%= @like_count %>likes</span>
<% end %>

app/views/likes/create.js.erb
$('.buttons_<%= @micropost.id %>').html("<%= j(render partial: 'likes/like') %>");

app/views/likes/destroy.js.erb
$('.buttons_<%= @micropost.id %>').html("<%= j(render partial: 'likes/like') %>");