config/routes.rb
Rails.application.routes.draw do
  root to: 'microposts#index'
  get '/', to: 'pages#home'
  get '/help', to: 'pages#help'
  get '/about', to: 'pages#about'
  get '/terms_of_service', to: 'pages#terms_of_service'
  get '/privacy', to: 'pages#privacy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get 'timeline', to: 'microposts#timeline'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  post 'likes/:micropost_id/create', to: 'likes#create', constraints: { micropost_id: /\d+/ }, as: :likes_create
  post 'likes/:micropost_id/destroy', to: 'likes#destroy', constraints: { micropost_id: /\d+/ }, as: :likes_destroy
end

app/views/shared/_card_micropost.html.erb
<% if @microposts.length == 0 %>
  <div class="card_post">まだ投稿がありません</div>
<% else %>
  <% @microposts.each do |micropost| %>
    <% user = User.find(micropost.user_id) %>
    <div class="card_post">
      <div class="navUserLogo">
        <%= link_to user_path(id: user.id), method: :get do %>
          <%# <%= image_tag User.find(micropost.user_id).image.url, alt: 'ユーザーのアイコン', class: 'image_user' %>
        <% end %>

        <span class="User_name_nav">
          <%= link_to user_path(id: user.id), method: :get do %>
            <%= User.find(micropost.user_id).name %>
          <% end %>
        </span>
      </div>
      <p class="Micropost_content_nav">
        <%= link_to micropost_path(id: micropost.id), method: :get do %>
          <%= micropost.content %>
        <% end %>
      </p>
      <% unless micropost.image == '/images/default.jpeg' %>
        <div class="image_micropost">
          <%= link_to micropost_path(id: micropost.id), method: :get do %>
            <%# <%= image_tag micropost.image, alt: '投稿写真', class: '' %>
          <% end %>
        </div>
      <% end %>
      <div class="actions-items">
        <span class="action" id="like_action-<%= micropost.id %>">
          <%= render 'likes/like', locals: {micropost: micropost} %>
        </span>
        <span class="action">
          <%= image_tag 'default.jpeg', alt: 時間 %>
          <span><%= time_ago_in_words(micropost.created_at) %>前</span>
        </span>
        <span class="action">
          <%= link_to micropost_path(id: micropost.id, method: :delete,
            data: {confirm: "投稿を削除してもよろしいでしょうか？"}) do %>
            <%= image_tag 'default.jpeg', alt: 消去 %>
          <% end %>
        </span>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_card_user.html.erb
<% if @users.length == 0 %>
  <div class="card_post">対象となるユーザーがまだおりません</div>
<% else %>
  <% @users.each do |user| %>
    <div class="card_post">
      <div class="navUserLogo">
        <% unless user.image == '/images/default.jpeg' %>
          <%= link_to user_path(id: user.id), method: :get do %>
            <%= image_tag '/images/default.jpeg', alt: 'ユーザーのアイコン', class: 'image_user' %>
          <% end %>
        <% end %>
      </div>
      <span class="User_name_nav">
        <%= link_to user_path(id: user.id), method: :get do %>
          <%= user.name %>
        <% end %>
      </span>
      <span class="stats">
        <%= render 'shared/stats'%>
      </span>
      <span class="col-md-8">
        <%= render 'follow_form' if logged_in? %>
      </span>
    </div>
  <% end %>
<% end %>

app/views/shared/_error_messages.html.erb
<%# <% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger alert-form-extend" role="alert">
            <%# <%= object.errors.count %>個のエラーがあります。
        </div>
        <ul>
            <%# <% object.errors.full_messages.each do |msg| %>
                 <%# <li><%= msg %></li>
            <%# <% end %>
        </ul>
    </div>
<%# <% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <div class="feed_items">
    <%= @feed_items.each do |feed_items| %>
      <% user = User.find(feed_items.user_id) %>
      <div class="card_post">
        <div class="navUserLogo">
          <%= link_to user_path(id: user.id), method: :get do %>
            <%# <%= image_tag User.find(micropost.user_id).image.url, alt: 'ユーザーのアイコン', class: 'image_user' %>
          <% end %>
          <span class="User_name_nav">
            <%= link_to user_path(id: user.id), method: :get do %>
              <%= User.find(feed_items.user_id).name %>
            <% end %>
          </span>
        </div>
        <p class="feed_content_nav">
          <%= link_to micropost_path(id: feed_items.id), method: :get do %>
            <%= feed_items.content %>
          <% end %>
        </p>
        <% unless feed_items.image == '/images/default.jpeg' %>
          <div class="image_micropost">
            <%= link_to micropost_path(id: feed_items.id), method: :get do %>
              <%# <%= image_tag micropost.image, alt: '投稿写真', class: '' %>
            <% end %>
          </div>
        <% end %>
        <div class="actions-items">
          <span class="action" id="like_action-<%= feed_items.id %>">
            <%= render 'likes/like', locals: {feed_items: @feed_items} %>
          </span>
          <span class="action">
            <%= image_tag 'default.jpeg', alt: 時間 %>
            <span><%= time_ago_in_words(feed_items.created_at) %>前</span>
          </span>
          <span class="action">
            <%= link_to micropost_path(id: feed_items.id, method: :delete,
              data: {confirm: "投稿を削除してもよろしいでしょうか？"}) do %>
              <%= image_tag 'default.jpeg', alt: 消去 %>
            <% end %>
          </span>
        </div>

      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<div class="container micropost-container">
  <h1>Micropost Form</h1>
  <%= form_with(model: @micropost, url: microposts_path, local: true) do |form| %>
    <%= render 'shared/error_messages', object: form.object %>
    <div class="form-group">
      <%= form.text_area :content, class: 'form-control', placeholder: "キャプションを書く" %>
    </div>
    <div class="form-group">
      <%= form.file_field :image %>
    </div>
    <div class="form-group">
      <%= form.submit "記録する", class: 'btn btn-info btn-lg form-submit' %>
    </div>
  <% end %>
</div>

app/views/shared/_stats.html.erb
<%= @user ||= current_user %>
<div class="stats">
  <a href="<%= user_path(@user) %>">
    <strong id="micropost" class="stat">
      <%= @user.microposts.count %>
    </strong>
    posted
  </a>
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" claa="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<span><%= link_to current_user.name, current_user %></span>