config/routes.rb
Rails.application.routes.draw do
  root to: 'microposts#index'
  get '/', to: 'pages#home'
  get '/help', to: 'pages#help'
  get '/about', to: 'pages#about'
  get '/terms_of_service', to: 'pages#terms_of_service'
  get '/privacy', to: 'pages#privacy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get 'timeline', to: 'microposts#timeline'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  post 'likes/:micropost_id/create', to: 'likes#create', constraints: { micropost_id: /\d+/ }, as: :likes_create
  post 'likes/:micropost_id/destroy', to: 'likes#destroy', constraints: { micropost_id: /\d+/ }, as: :likes_destroy
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="container">
    <ul>
      <li><%= link_to 'kodawarimediaに関して', about_path, class: '', method: :get %></li>
      <li><%= link_to '利用規約', terms_of_service_path, class: '', method: :get %></li>
      <li><%= link_to 'プライバシーポリシー', privacy_path, class: '', method: :get %></li>
    </ul>
    <p><small>&copy; 2020 KODAWARIMEDIA All rights reserved.</small></p>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="navbarTop">
    <div class="siteLogo">
      <%= link_to image_tag('kodawarimedia-1.jpeg', width: 50), root_url %>
    </div>

    <div class="navbarTop_nav dropdown">
      <button class="nav-link header_sub_menu_item" id="dropdownMenuButton button-group" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-user-cog"></i>
      </button>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <% if logged_in? %>
          <%= link_to "プロフィール", user_path(current_user), class: 'nav-link dropdown-item' %>
          <%= link_to "プロフフィール編集", edit_user_path(current_user), class:'nav-link dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to "ログアウト", logout_path, method: :delete, class:'nav-link dropdown-item' %>
        <% else %>
          <%= link_to "新しくはじめる", signup_path, class:'nav-link dropdown-item' %>
          <%= link_to "ログイン", login_path, class:'nav-link dropdown-item' %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="navbarMenu nav">
    <ul>
      <li><%= link_to "ホーム", root_url %></li>
      <% if logged_in? %>
        <li><%= link_to "タイムライン", timeline_path %></li>
        <li><%= link_to "スキ", root_path %></li>
        <li><%= link_to "ユーザー", users_path %></li>
        <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "新しくはじめる", signup_path %></li>
        <li><%= link_to "ログイン", login_path %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/_pagenate_bottom.html.erb
<% if @users == nil && @feed_items == nil %>
  <div class="wrapper_pagenate bottom">
    <%= paginate @microposts %>
  </div>
<% elsif @users == nil %>
  <div class="wrapper_pagenate bottom">
    <%= paginate @feed_items %>
  </div>
<% else %>
  <div class="wrapper_pagenate bottom">
    <%= paginate @users %>
  </div>
<% end %>

app/views/layouts/_pagenate_top.html.erb
<% if @users == nil && @feed_items == nil %>
  <div class="wrapper_pagenate top">
    <%= paginate @microposts %>
  </div>
<% elsif @users == nil %>
  <div class="wrapper_pagenate top">
    <%= paginate @feed_items %>
  </div>
<% else %>
  <div class="wrapper_pagenate top">
    <%= paginate @users %>
  </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="sub-item">
  <%= render 'shared/user_info' %>
  <%= render 'shared/stats' %>
  <%= render 'shared/micropost_form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <%= tag.div message, class: "alert alert-#{message_type}" %>
    <% end %>
    <div class="main">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>